/* eslint-disable react/no-unknown-property */
/* eslint-disable no-unused-vars */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/mom.glb 
*/

import  { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/mom.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" position={[0, 0.005, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="model_0" geometry={nodes.model_0.geometry} material={materials['Material.002']} skeleton={nodes.model_0.skeleton} />
          <skinnedMesh name="model_1" geometry={nodes.model_1.geometry} material={materials['Material.001']} skeleton={nodes.model_1.skeleton} />
          <skinnedMesh name="model_2" geometry={nodes.model_2.geometry} material={materials['Material.003']} skeleton={nodes.model_2.skeleton} />
        </group>
        <group name="Circle" position={[0.012, 0.011, 0]} scale={0.001} />
      </group>
    </group>
  )
}

useGLTF.preload('/mom.glb')
